version = 0.1
[default.deploy.parameters]
stack_name = "sam-inventory"
resolve_s3 = true
s3_prefix = "sam-inventory"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" AdminEmail=\"uncertain.chicken.pgzf@letterprotect.com\" DomainName=\"domain@domain.com\" EmailSender=\"sensitive.ocelot.fflb@letterhaven.net\" AdminFirstName=\"TestAdmin\" AdminLastName=\"LastName\""
image_repositories = []
